/*-----------------------------
 * ■ index.jsとは
 * トップページ(/)となるファイル
 * Nuxtでいうところのindex.vue
 * Head = metaデータを記入できるコンポーネント
 * Link = linkをするコンポーネント
 * 例) <Link href="https://nextjs.org"><a>Next.js!</a></Link>
 *
 * Layout = サイト全体をwrapするコンポーネントの読み込み
 *
 *----------------------------------*/

import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Layout from "../components/layout";
import Side from "../components/Side";
import { client } from "../libs/client";
import styles from "../styles/Home.module.css";

export default function Home({ photo }) {
  /*----------------------------
   * ループ用の配列
   * ------------------------------*/
  console.log(photo);
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={styles.containerFlex}>
          <Side />
          <div className={styles.containerRight}>
            <h2 className={styles.containerTitle}>KRAFT PhotoStock</h2>
            <h3 className={styles.containerSub}>21:48:56</h3>
            {/* mapで配列を回す(v-for的な感じ) */}
            <div className={styles.containerCards}>
              {photo.map((photo) => {
                return (
                  <div className={styles.card} key={photo.id}>
                    <img src={photo.img.url} alt="" />
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      </div>
    </Layout>
  );
}

export const getStaticProps = async () => {
  const data = await client.get({ endpoint: "photo" });

  return {
    props: {
      photo: data.contents,
    },
  };
};
